
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOT EXTENSION HTTP1 NAME and contains excludes get http orDATA : get URI CONSTRAINT\n            | get URIURI : URLURL : http HTTP1 NAME DOT EXTENSIONCONSTRAINT : contains NAME\n                  | excludes NAME\n                  | contains NAME OPERATOR CONSTRAINT\n                  | excludes NAME OPERATOR CONSTRAINTOPERATOR : and\n                | or'
    
_lr_action_items = {'http':([2,],[4,]),'EXTENSION':([13,],[18,]),'contains':([3,5,14,15,16,17,18,],[-3,7,-9,7,-10,7,-4,]),'or':([11,12,],[16,16,]),'get':([0,],[2,]),'DOT':([10,],[13,]),'and':([11,12,],[14,14,]),'NAME':([6,7,9,],[10,11,12,]),'$end':([1,3,5,8,11,12,18,19,20,],[0,-3,-2,-1,-5,-6,-4,-7,-8,]),'excludes':([3,5,14,15,16,17,18,],[-3,9,-9,9,-10,9,-4,]),'HTTP1':([4,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'URL':([2,],[3,]),'OPERATOR':([11,12,],[15,17,]),'URI':([2,],[5,]),'DATA':([0,],[1,]),'CONSTRAINT':([5,15,17,],[8,19,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> DATA","S'",1,None,None,None),
  ('DATA -> get URI CONSTRAINT','DATA',3,'p_DATA','parser.py',16),
  ('DATA -> get URI','DATA',2,'p_DATA','parser.py',17),
  ('URI -> URL','URI',1,'p_URI','parser.py',20),
  ('URL -> http HTTP1 NAME DOT EXTENSION','URL',5,'p_URL','parser.py',24),
  ('CONSTRAINT -> contains NAME','CONSTRAINT',2,'p_CONSTRAINT','parser.py',29),
  ('CONSTRAINT -> excludes NAME','CONSTRAINT',2,'p_CONSTRAINT','parser.py',30),
  ('CONSTRAINT -> contains NAME OPERATOR CONSTRAINT','CONSTRAINT',4,'p_CONSTRAINT','parser.py',31),
  ('CONSTRAINT -> excludes NAME OPERATOR CONSTRAINT','CONSTRAINT',4,'p_CONSTRAINT','parser.py',32),
  ('OPERATOR -> and','OPERATOR',1,'p_OPERATOR','parser.py',35),
  ('OPERATOR -> or','OPERATOR',1,'p_OPERATOR','parser.py',36),
]
